#%RAML 1.0
version: v1
title: Trafika

types: 
  Proizvod: !include data_types/ProizvodDataType.raml
  Racun: !include data_types/RacunDataType.raml
  Prodavac: !include data_types/ProdavacDataType.raml
  Menadzer: !include data_types/MenadzerDataType.raml
  Dobavljac: !include data_types/DobavljacDataType.raml
  Porudzbina: !include data_types/PorudzbinaDataType.raml
  Izvestaj: !include data_types/IzvestajDataType.raml
  StavkaPorudzbine: !include data_types/StavkaPorudzbineDataType.raml
  StavkaRacuna: !include data_types/StavkaRacunaDataType.raml
  Korisnik: !include data_types/KorisnikDataType.raml
  Proizvodjac: !include data_types/ProizvodjacDataType.raml
  VrstaProizvoda: !include data_types/VrstaProizvodaDataType.raml

/proizvod:
  get:
#    displayName: Get flights
#    queryParameters:
#      code:
#        displayName: Destination airport code
#        required: false
#        enum: 
#          - SFO
#          - LAX
#          - PDX
#          - CLE
#          - PDF
#      airline:
#        displayName: Airline
#        required: false
#        enum: 
#          - united
#          - delta
#          - american
    responses: 
      200:
        body: 
          application/json:
            type: Proizvod[]
            example: !include examples/ProizvodiExample.raml

  post:
    body: 
      application/json:
        type: Proizvod
        example: !include examples/ProizvodExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Proizvod dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Proizvod
              example: !include examples/ProizvodExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvod obrisan
    put:
      body:
        application/json:
          type: Proizvod
          example: !include examples/ProizvodExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvod azuriran
                
/racun:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Racun[]
            example: !include examples/RacuniExample.raml

  post:
    body: 
      application/json:
        type: Racun
        example: !include examples/RacunExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Racun dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Racun
              example: !include examples/RacunExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Racun obrisan
    put:
      body:
        application/json:
          type: Racun
          example: !include examples/RacunExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Racun azuriran
                
/prodavac:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Prodavac[]
            example: !include examples/ProdavciExample.raml

  post:
    body: 
      application/json:
        type: Prodavac
        example: !include examples/ProdavacExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Prodavac dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Prodavac
              example: !include examples/ProdavacExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Prodavac obrisan
    put:
      body:
        application/json:
          type: Prodavac
          example: !include examples/ProdavacExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Prodavac azuriran
                
/menadzer:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Menadzer[]
            example: !include examples/MenadzeriExample.raml

  post:
    body: 
      application/json:
        type: Menadzer
        example: !include examples/MenadzerExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Menadzer dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Menadzer
              example: !include examples/MenadzerExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Menadzer obrisan
    put:
      body:
        application/json:
          type: Menadzer
          example: !include examples/MenadzerExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Menadzer azuriran
                
/dobavljac:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Dobavljac[]
            example: !include examples/DobavljaciExample.raml

  post:
    body: 
      application/json:
        type: Dobavljac
        example: !include examples/DobavljacExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Dobavljac dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Dobavljac
              example: !include examples/DobavljacExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Dobavljac obrisan
    put:
      body:
        application/json:
          type: Dobavljac
          example: !include examples/DobavljacExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Dobavljac azuriran
                
/porudzbina:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Porudzbina[]
            example: !include examples/PorudzbineExample.raml

  post:
    body: 
      application/json:
        type: Porudzbina
        example: !include examples/PorudzbinaExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Porudzbina dodata

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Porudzbina
              example: !include examples/PorudzbinaExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Porudzbina obrisana
    put:
      body:
        application/json:
          type: Porudzbina
          example: !include examples/PorudzbinaExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Porudzbina azurirana
                
/izvestaj:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Izvestaj[]
            example: !include examples/IzvestajiExample.raml

  post:
    body: 
      application/json:
        type: Izvestaj
        example: !include examples/IzvestajExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Izvestaj dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Izvestaj
              example: !include examples/IzvestajExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Izvestaj obrisan
    put:
      body:
        application/json:
          type: Izvestaj
          example: !include examples/IzvestajExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Izvestaj azuriran
                
/stavkaRacuna:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: StavkaRacuna[]
            example: !include examples/StavkeRacunaExample.raml

  post:
    body: 
      application/json:
        type: StavkaRacuna
        example: !include examples/StavkaRacunaExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Stavka racuna dodata

  /{racunID}/{proizvodID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: StavkaRacuna
              example: !include examples/StavkaRacunaExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka racuna obrisana
    put:
      body:
        application/json:
          type: StavkaRacuna
          example: !include examples/StavkaRacunaExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka racuna azurirana
                
/stavkaPorudzbine:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: StavkaPorudzbine[]
            example: !include examples/StavkePorudzbineExample.raml

  post:
    body: 
      application/json:
        type: StavkaPorudzbine
        example: !include examples/StavkaPorudzbineExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Stavka porudzbine dodata

  /{porudzbinaID}/{proizvodID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: StavkaPorudzbine
              example: !include examples/StavkaPorudzbineExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka porudzbine obrisana
    put:
      body:
        application/json:
          type: StavkaPorudzbine
          example: !include examples/StavkaPorudzbineExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka porudzbine azurirana
                
/korisnik:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Korisnik[]
            example: !include examples/KorisniciExample.raml

  post:
    body: 
      application/json:
        type: Korisnik
        example: !include examples/KorisnikExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Korisnik dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Korisnik
              example: !include examples/KorisnikExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Korisnik obrisan
    put:
      body:
        application/json:
          type: Korisnik
          example: !include examples/KorisnikExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Korisnik azuriran
                
/proizvodjac:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Proizvodjac[]
            example: !include examples/ProizvodjaciExample.raml

  post:
    body: 
      application/json:
        type: Proizvodjac
        example: !include examples/ProizvodjacExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Proizvodjac dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Proizvodjac
              example: !include examples/ProizvodjacExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvodjac obrisan
    put:
      body:
        application/json:
          type: Proizvodjac
          example: !include examples/ProizvodjacExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvodjac azuriran
                
/vrstaProizvoda:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: VrstaProizvoda[]
            example: !include examples/VrsteProizvodaExample.raml

  post:
    body: 
      application/json:
        type: VrstaProizvoda
        example: !include examples/VrstaProizvodaExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Vrsta proizvoda dodata

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: VrstaProizvoda
              example: !include examples/VrstaProizvodaExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Vrsta proizvoda obrisana
    put:
      body:
        application/json:
          type: VrstaProizvoda
          example: !include examples/VrstaProizvodaExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Vrsta proizvoda azurirana