#%RAML 1.0
version: v1
title: Trafika

types: 
  Proizvod: !include data_types/ProizvodDataType.raml
  Racun: !include data_types/RacunDataType.raml
  Prodavac: !include data_types/ProdavacDataType.raml
  Menadzer: !include data_types/MenadzerDataType.raml
  Dobavljac: !include data_types/DobavljacDataType.raml
  Porudzbina: !include data_types/PorudzbinaDataType.raml
  Izvestaj: !include data_types/IzvestajDataType.raml
  StavkaPorudzbine: !include data_types/StavkaPorudzbineDataType.raml
  StavkaRacuna: !include data_types/StavkaRacunaDataType.raml
  Korisnik: !include data_types/KorisnikDataType.raml
  Proizvodjac: !include data_types/ProizvodjacDataType.raml
  VrstaProizvoda: !include data_types/VrstaProizvodaDataType.raml

/proizvod:
  get:
    displayName: Get proizvodi
    queryParameters:
      nazivProizvoda:
        displayName: Naziv
        type: string
        description: Naziv proizvoda
        example: Plazma
        required: false
      cena:
        displayName: Cena
        type: integer
        description: Cena proizvoda
        example: 100
        required: false
      tipPakovanja:
        displayName: Tip pakovanja
        type: string
        description: Tip pakovanja proizvoda
        example: kutija
        required: false
      velicinaPakovanja:
        displayName: Veličina pakovanja
        type: string
        description: Veličina pakovanja proizvoda
        example: redovno
        required: false
      barKod:
        displayName: Bar kod
        type: string
        description: Bar kod proizvoda
        example: '00143234'
        required: false
      masa:
        displayName: Masa
        type: number
        description: Masa proizvoda
        example: 100
        required: false
      proizvodjacID:
        displayName: Proizvođač
        type: integer
        description: Proizvođač proizvoda
        example: 1
        required: false
      vrstaProizvodaID:
        displayName: Vrsta proizvoda
        type: integer
        description: Vrsta proizvoda
        example: 1
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Proizvod[]
            example: !include examples/ProizvodiExample.raml

  post:
    body: 
      application/json:
        type: Proizvod
        example: !include examples/ProizvodExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Proizvod dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Proizvod
              example: !include examples/ProizvodExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvod obrisan
    put:
      body:
        application/json:
          type: Proizvod
          example: !include examples/ProizvodExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvod azuriran
                
/racun:
  get:
    queryParameters:
      vremeIzdavanja:
        displayName: Vreme izdavanja
        type: datetime-only
        description: Vreme izdavanja računa
        example: 2015-07-04T21:00:00
        required: false
      mestoIzdavanja:
        displayName: Mesto izdavanja
        type: string
        description: Mesto izdavanja računa
        example: Beograd
        required: false
      ukupanIznosRacuna:
        displayName: Ukupan iznos
        type: number
        description: Ukupan iznos računa
        example: 123
        required: false
      nazivProdavnice:
        displayName: Naziv prodavnice
        type: string
        description: Naziv prodavnice koja je izdala račun
        example: Trafika BMB
        required: false
      nacinPlacanja:
        displayName: Način plaćanja
        type: string
        description: Način plaćanja računa
        enum: 
          - gotovina
          - kartica
        required: false
      brojRacuna:
        displayName: Broj
        type: string
        description: Broj računa
        example: aw3432342432
        required: false
      tipRacuna:
        displayName: Tip
        type: string
        description: Tip računa
        example: Dopuna
        required: false
      prodavacID:
        displayName: Prodavac
        type: integer
        description: Prodavac koji je izdao račun
        example: 1
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Racun[]
            example: !include examples/RacuniExample.raml

  post:
    body: 
      application/json:
        type: Racun
        example: !include examples/RacunExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Racun dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Racun
              example: !include examples/RacunExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Racun obrisan
    put:
      body:
        application/json:
          type: Racun
          example: !include examples/RacunExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Racun azuriran
                
/prodavac:
  get:
    queryParameters:
      ime:
        displayName: Ime
        type: string
        description: Ime prodavca
        example: Petar
        required: false
      prezime:
        displayName: Ime
        type: string
        description: Ime prodavca
        example: Petar
        required: false
      pol:
        displayName: Pol
        type: string
        description: Pol prodavca
        enum: 
          - musko
          - zensko
        required: false
      datumRodjenja:
        displayName: Datum rođenja
        type: date-only
        description: Datum rođenja prodavca
        example: 1999-05-23
        required: false
      adresaStanovanja:
        displayName: Adresa stanovanja
        type: string
        description: Adresa stanovanja prodavca
        example: Ohridska 12
        required: false
      telefon:
        displayName: Telefon
        type: string
        description: Telefon prodavca
        example: '0631113452'
        required: false
      JMBG:
        displayName: JMBG
        type: string
        description: JMBG prodavca
        example: '0811998910053'
        required: false
      datumZaposlenja:
        displayName: Datum zaposlenja
        type: date-only
        description: Datum zaposlenja prodavca
        example: 2019-05-23
        required: false
      strucnaSprema:
        displayName: Stručna sprema
        type: string
        description: Stručna sprema prodavca
        example: srednja škola
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Prodavac[]
            example: !include examples/ProdavciExample.raml

  post:
    body: 
      application/json:
        type: Prodavac
        example: !include examples/ProdavacExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Prodavac dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Prodavac
              example: !include examples/ProdavacExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Prodavac obrisan
    put:
      body:
        application/json:
          type: Prodavac
          example: !include examples/ProdavacExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Prodavac azuriran
                
/menadzer:
  get:
    queryParameters:
      adresaKancelarije:
        displayName: Adresa kancelarije
        type: string
        description: Adresa kancelarije menadžera
        example: Banatska BB
        required: false
      brojKancelarije:
        displayName: Broj kancelarije
        type: string
        description: Broj kancelarije menadžera
        example: c12a
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Menadzer[]
            example: !include examples/MenadzeriExample.raml

  post:
    body: 
      application/json:
        type: Menadzer
        example: !include examples/MenadzerExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Menadzer dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Menadzer
              example: !include examples/MenadzerExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Menadzer obrisan
    put:
      body:
        application/json:
          type: Menadzer
          example: !include examples/MenadzerExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Menadzer azuriran
                
/dobavljac:
  get:
    queryParameters:
      skraceniNaziv:
        displayName: Skraćeni naziv
        type: string
        description: Skraceni naziv dobavljača
        example: RAS
        required: false
      punNaziv:
        displayName: Pun naziv
        type: string
        description: Pun naziv dobavljača
        example: Ringier Axel Springier
        required: false
      kontaktDobavljaca:
        displayName: Kontakt
        type: string
        description: Kontakt dobavljača
        example: '024234444'
        required: false
      adresaDobavljaca:
        displayName: Adresa
        type: string
        description: Adresa dobavljača
        example: Banatska BB
        required: false
      grad:
        displayName: Grad
        type: string
        description: Grad dobavljača
        example: Sombor
        required: false
      drzava:
        displayName: Država
        type: string
        description: Država dobavljača
        example: Srbija
        required: false
      postanskiBroj:
        displayName: Poštanski broj
        type: string
        description: Poštanski broj dobavljača
        example: '2434332'
        required: false
      PIB:
        displayName: PIB
        type: integer
        description: PIB dobavljača
        example: 111111111
        required: false
      kontaktOsoba:
        displayName: Kontakt osoba
        type: string
        description: Kontakt osoba dobavljača
        example: Pera Peric
        required: false
      brojZiroRacuna:
        displayName: Broj žiro računa
        type: string
        description: Broj žiro računa dobavljača
        example: 3ea032324324
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Dobavljac[]
            example: !include examples/DobavljaciExample.raml

  post:
    body: 
      application/json:
        type: Dobavljac
        example: !include examples/DobavljacExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Dobavljac dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Dobavljac
              example: !include examples/DobavljacExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Dobavljac obrisan
    put:
      body:
        application/json:
          type: Dobavljac
          example: !include examples/DobavljacExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Dobavljac azuriran
                
/porudzbina:
  get:
    queryParameters:
      datumPorucivanja:
        displayName: Datum poručivanja
        type: date-only
        description: Datum poručivanja porudžbine
        example: 2015-05-25
        required: false
      datumIsporuke:
        displayName: Datum isporuke
        type: date-only
        description: Datum isporuke porudžbine
        example: 2015-05-30
        required: false
      ukupanIznosPorudzbine:
        displayName: Ukupan iznos
        type: number
        description: Ukupan iznos porudžbine
        example: 12323
        required: false
      statusPorudzbine:
        displayName: Status
        type: string
        description: Status porudžbine
        enum: 
          - poruceno
          - kompletirano
          - reklamacija
        required: false
      dobavljacID:
        displayName: Dobavljač
        type: integer
        description: Dobavljač porudžbine
        example: 1
        required: false
      menadzerID:
        displayName: Menadžer
        type: integer
        description: Menadžer porudžbine
        example: 1
        required: false
      prodavacID:
        displayName: Prodavac
        type: integer
        description: Prodavac porudžbine
        example: 1
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Porudzbina[]
            example: !include examples/PorudzbineExample.raml

  post:
    body: 
      application/json:
        type: Porudzbina
        example: !include examples/PorudzbinaExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Porudzbina dodata

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Porudzbina
              example: !include examples/PorudzbinaExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Porudzbina obrisana
    put:
      body:
        application/json:
          type: Porudzbina
          example: !include examples/PorudzbinaExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Porudzbina azurirana
                
/izvestaj:
  get:
    queryParameters:
      promet:
        displayName: Promet
        type: number
        description: Promet
        example: 123
        required: false
      brojKupovina:
        displayName: Broj kupovina
        type: integer
        description: Broj kupovina
        example: 12
        required: false
      datumOd:
        displayName: Datum od
        type: date-only
        description: Datum od
        example: 2015-05-23
        required: false
      datumDo:
        displayName: Datum do
        type: date-only
        description: Datum do
        example: 2017-05-23
        required: false
      menadzerID:
        displayName: Menadžer
        type: integer
        description: Menadžer
        example: 1
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Izvestaj[]
            example: !include examples/IzvestajiExample.raml

  post:
    body: 
      application/json:
        type: Izvestaj
        example: !include examples/IzvestajExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Izvestaj dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Izvestaj
              example: !include examples/IzvestajExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Izvestaj obrisan
    put:
      body:
        application/json:
          type: Izvestaj
          example: !include examples/IzvestajExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Izvestaj azuriran
                
/stavkaRacuna:
  get:
    queryParameters:
      kolicinaProizvoda:
        displayName: Količina proizvoda
        type: integer
        description: Količina proizvoda
        example: 12
        required: false
      prodajnaCena:
        displayName: Prodajna cena
        type: number
        description: Prodajna cena
        example: 123
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: StavkaRacuna[]
            example: !include examples/StavkeRacunaExample.raml

  post:
    body: 
      application/json:
        type: StavkaRacuna
        example: !include examples/StavkaRacunaExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Stavka racuna dodata

  /{racunID}/{proizvodID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: StavkaRacuna
              example: !include examples/StavkaRacunaExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka racuna obrisana
    put:
      body:
        application/json:
          type: StavkaRacuna
          example: !include examples/StavkaRacunaExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka racuna azurirana
                
/stavkaPorudzbine:
  get:
    queryParameters:
      kolicina:
        displayName: Količina proizvoda
        type: integer
        description: Količina proizvoda
        example: 12
        required: false
      nabavnaCena:
        displayName: Nabavna cena
        type: number
        description: Nabavna cena
        example: 123
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: StavkaPorudzbine[]
            example: !include examples/StavkePorudzbineExample.raml

  post:
    body: 
      application/json:
        type: StavkaPorudzbine
        example: !include examples/StavkaPorudzbineExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Stavka porudzbine dodata

  /{porudzbinaID}/{proizvodID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: StavkaPorudzbine
              example: !include examples/StavkaPorudzbineExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka porudzbine obrisana
    put:
      body:
        application/json:
          type: StavkaPorudzbine
          example: !include examples/StavkaPorudzbineExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Stavka porudzbine azurirana
                
/korisnik:
  get:
    queryParameters:
      email:
        displayName: Email
        type: string
        description: Email korisnika
        example: vukan.markovic97@gmail.com
        required: false
      uloga:
        displayName: Uloga
        type: string
        description: Uloga korisnika
        enum: 
          - prodavac
          - dobavljac
          - menadzer
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Korisnik[]
            example: !include examples/KorisniciExample.raml

  post:
    body: 
      application/json:
        type: Korisnik
        example: !include examples/KorisnikExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Korisnik dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Korisnik
              example: !include examples/KorisnikExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Korisnik obrisan
    put:
      body:
        application/json:
          type: Korisnik
          example: !include examples/KorisnikExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Korisnik azuriran
                
/proizvodjac:
  get:
    queryParameters:
      nazivProizvodjaca:
        displayName: Naziv
        type: string
        description: Naziv proizvođača
        example: Imlek
        required: false
      kontaktProizvodjaca:
        displayName: Kontakt
        type: string
        description: Kontakt proizvođača
        example: '32324443'
        required: false
      adresaProizvodjaca:
        displayName: Adresa
        type: string
        description: Adresa proizvođača
        example: Jugovića 2
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: Proizvodjac[]
            example: !include examples/ProizvodjaciExample.raml

  post:
    body: 
      application/json:
        type: Proizvodjac
        example: !include examples/ProizvodjacExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Proizvodjac dodat

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: Proizvodjac
              example: !include examples/ProizvodjacExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvodjac obrisan
    put:
      body:
        application/json:
          type: Proizvodjac
          example: !include examples/ProizvodjacExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Proizvodjac azuriran
                
/vrstaProizvoda:
  get:
    queryParameters:
      nazivVrsteProizvoda:
        displayName: Naziv
        type: string
        description: Naziv vrste proizvoda
        example: štampa
        required: false
    responses: 
      200:
        body: 
          application/json:
            type: VrstaProizvoda[]
            example: !include examples/VrsteProizvodaExample.raml

  post:
    body: 
      application/json:
        type: VrstaProizvoda
        example: !include examples/VrstaProizvodaExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Vrsta proizvoda dodata

  /{ID}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: VrstaProizvoda
              example: !include examples/VrstaProizvodaExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Vrsta proizvoda obrisana
    put:
      body:
        application/json:
          type: VrstaProizvoda
          example: !include examples/VrstaProizvodaExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Vrsta proizvoda azurirana