#%RAML 1.0 NamedExample
value:
  -
    porudzbinaID: 1
    datumPorucivanja: 2015-05-25
    datumIsporuke: 2015-05-30
    ukupanIznosPorudzbine: 12323
    statusPorudzbine: 'poruceno'
    dobavljacID: 1
    menadzerID: 1 
    prodavacID: 1 
    active: 1
  -
    porudzbinaID: 2
    datumPorucivanja: 2015-05-25
    datumIsporuke: 2015-05-30
    ukupanIznosPorudzbine: 12323
    statusPorudzbine: 'poruceno'
    dobavljacID: 1
    menadzerID: 1 
    prodavacID: 1 
    active: 1