#%RAML 1.0 NamedExample
value:
  -
    proizvodjacID: 1
    nazivProizvodjaca: 'Imlek'
    kontaktProizvodjaca: '32324443' 
    adresaProizvodjaca: 'Jugovića 2'
  -
    proizvodjacID: 2
    nazivProizvodjaca: 'Dukat'
    kontaktProizvodjaca: '32324489943' 
    adresaProizvodjaca: 'Lipov lad 2'