#%RAML 1.0 NamedExample
value:
  -
    racunID: 1 
    vremeIzdavanja: 2019-06-08 16:31:23
    mestoIzdavanja: Novi Sad
    iznos: 35
    kolicina: 1  
    proizvodID: 1  
    active: 0
  -
    racunID: 2
    vremeIzdavanja: 2014-02-07 13:12:23
    mestoIzdavanja:  Beograd
    iznos: 180
    kolicina: 2 
    proizvodID: 2  
    active: 1