#%RAML 1.0 NamedExample
value:
  -
    racunID: 1
    vremeIzdavanja: 2015-07-04T21:00:00
    mestoIzdavanja: 'Beograd'
    ukupanIznosRacuna: 123 
    nazivProdavnice: 'Trafika BMB'
    nacinPlacanja: 'gotovina'
    brojRacuna: '3432342432'
    prodavacID: 1
  -
    racunID: 2
    vremeIzdavanja: 2015-07-04T21:00:00
    mestoIzdavanja: 'Beograd'
    ukupanIznosRacuna: 123 
    nazivProdavnice: 'Trafika BMB'
    nacinPlacanja: 'gotovina'
    brojRacuna: '34323432'
    prodavacID: 1